export const LOAD_ITEMS = 'LOAD_ITEMS'
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR = 'CLEAR'
export const CHECKOUT = 'CHECKOUT'